#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=gc
environment_variables=( )
configure_arguments=( --enable-cplusplus )

source shared/basic.zsh
