#!/bin/zsh

source shared/helpers.zsh
source shared/make_package.zsh
source shared/git.zsh

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 PACKAGE_VERSION"
    exit 2
fi

name=spitbol-x64

_package_version="${package_version:-${1}}"
_targeted_host=x86_64-unknown-linux-gnu

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

packname="${name}-${_package_version}"
src_tarball=`find_src_tarball "${abs_src_tarball_dir}/${packname}"` || ${bail_out}
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_srcdirs_dir}/${packname}"
abs_builddir="${abs_srcdir}"
abs_destdir="${abs_srcdir}/___dest___"

mkdir -p "${abs_srcdirs_dir}"
rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
tar -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}

git_check_out "${abs_src_tarball_dir}"/spitbol-docs.git "«live»" || ${bail_out}

mv "${abs_srcdirs_dir}"/{"x64-${_package_version}","${packname}"} || ${bail_out}

mkdir -p "${abs_builddir}" || ${bail_out}
(

    cd "${abs_builddir}" || ${bail_out}

    make clean || ${bail_out}
    make || ${bail_out}
    ./sanity-check || ${bail_out}

    install -d "${abs_destdir}"/usr/local/{bin,share/spitbol,share/{man/man1,doc/spitbol}} \
        || ${bail_out}
    install -m 755 bin/sbl "${abs_destdir}"/usr/local/bin || ${bail_out}
    install -m 644 demos/* "${abs_destdir}"/usr/local/share/spitbol || ${bail_out}
    install -m 644 spitbol.1 "${abs_destdir}"/usr/local/share/man/man1 || ${bail_out}
    (cd "${abs_destdir}"/usr/local/share/man/man1 &&
         ln -s spitbol.1 sbl.1 || ${bail_out}) || ${bail_out}
    (cd "${abs_destdir}"/usr/local/bin &&
         ln -s sbl spitbol || ${bail_out}) || ${bail_out}
    install -m 644 "${abs_src_tarball_dir}"/spitbol-docs.git/* \
            "${abs_destdir}"/usr/local/share/doc/spitbol || ${bail_out}

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
