#!/bin/zsh

source shared/make_package.zsh
source shared/git.zsh

if [[ $# -ne 5 ]]; then
    echo "Usage: $0 REVISION TARGETED_HOST CHECK ARCH TUNE"
    exit 3
fi

name=chez-exe

_revision="${1}"
_targeted_host="${2}"
_check="${3}"
_arch="${4}"
_tune="${5}"

_chez_version=`scheme --version | head -c-1`
_bootpath=/usr/local/lib/csv${_chez_version}/ta6le

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

abs_repo_dir="${abs_src_tarball_dir}/${name}.git"
git_check_out "${abs_repo_dir}" "${_revision}"

packname="${name}-${_revision}"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_repo_dir}"
abs_builddir="${abs_srcdirs_dir}/${packname}/___build___"
abs_destdir="${abs_srcdirs_dir}/${packname}/___dest___"

abs_filesdir=`realpath "${PWD}"`/files

rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
install -d "${abs_builddir}" || ${bail_out}
(

    cd "${abs_builddir}" || ${bail_out}

    # Copy the sources.
    cp --archive --link --update=none "${abs_srcdir}"/* "${abs_builddir}" \
        || ${bail_out}

    patch -p1 < "${abs_filesdir}"/"${name}"/"${name}".Makefile.patch

    env CFLAGS="-pipe -fPIC -O2 -march=${_arch} -mtune=${_tune}" \
        scheme --script gen-config.ss --bootpath "${_bootpath}" \
        || ${bail_out}

    abs_bindir="${abs_destdir}"/usr/local/bin
    abs_libdir="${abs_destdir}"/usr/local/lib
    abs_docdir="${abs_destdir}"/usr/local/share/doc/"${name}"

    install -d "${abs_bindir}" || ${bail_out}
    install -m 755 compile-chez-program "${abs_bindir}" || ${bail_out}
    install -d "${abs_libdir}" || ${bail_out}
    install -m 644 {full,petite}-chez.a "${abs_libdir}" || ${bail_out}
    install -d "${abs_docdir}" || ${bail_out}
    install -m 644 LICENSE NOTICE README.md "${abs_docdir}" || ${bail_out}

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
