#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=enscript

environment_variables=(
    CFLAGS="${CFLAGS}${CFLAGS+ }-std=gnu89"
)
configure_arguments=(
    --with-media=Letter
    --with-ps-level=2
    --disable-nls
)

source shared/basic.zsh
