#!/bin/zsh

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 PACKAGE_VERSION"
    exit 2
fi

name=xmlada
targeted_host=x86_64-unknown-linux-gnu

ban_out_of_source_build=yes
ban_check=yes
ban_enable_silent_rules=yes

environment_variables=( )
configure_arguments=( )
make_arguments=( all GPRBUILD_OPTIONS='-v' )

source shared/basic.zsh
