#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=rlwrap

environment_variables=( )
configure_arguments=(
    --enable-homegrown-redisplay=no
    --enable-multibyte-aware=yes
    --enable-spy-on-readline=yes
    --enable-proc-mountpoint=/proc
    --with-libptytty=yes
)

source shared/basic.zsh
