#!/bin/zsh

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 PACKAGE_VERSION"
    exit 2
fi

name=json-c

_package_version="${1}"
_targeted_host=x86_64-unknown-linux-gnu

tar=( tar --format=posix )
bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

packname="${name}-${_package_version}"
src_tarball="${abs_src_tarball_dir}/${packname}.tar.gz"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.xz"
abs_srcdir="${abs_srcdirs_dir}/${packname}"
abs_builddir="${abs_srcdir}/«build»"
abs_destdir="${abs_srcdir}/«dest»"

mkdir -p "${abs_srcdirs_dir}"
rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
${tar} -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}
mkdir -p "${abs_builddir}" || ${bail_out}
(
    cd "${abs_builddir}" || ${bail_out}
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
          -DCMAKE_INSTALL_RPATH=/usr/local/lib \
          -DBUILD_SHARED_LIBS=ON \
          -DBUILD_STATIC_LIBS=ON \
          -DDISABLE_WERROR=ON \
          .. || ${bail_out}
    make || ${bail_out}
    make install DESTDIR="${abs_destdir}" || ${bail_out}
) || ${bail_out}
mkdir -p "${abs_bin_tarball_dir}" || ${bail_out}
${tar} -cvaf "${bin_tarball}" -C "${abs_destdir}" usr || ${bail_out}
