#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=gnutls

templib=`mktemp -d || exit 1` || exit 1
echo 'GROUP ( /usr/local/lib/libunistring.a /usr/local/lib/libtasn1.a -ldl -lhogweed -lnettle /usr/local/lib/libgmp.so )' \
     > "${templib}/libscript.so"

environment_variables=( )
configure_arguments=(

    --without-p11-kit

    # Our libtasn1 is statically compiled.
    --without-included-libtasn1

    # Our libunistring is statically compiled
    --without-included-unistring

    --enable-shared
    --enable-static

)
make_arguments=( LIBS="-L${templib} -lscript" )

source shared/basic.zsh

#
# Remove libscript.so from .la files.
#
find "${abs_destdir}" -name '*.la' |
    xargs sed -i -E "s:(-L${templib}|-lscript)::g" \
        || ${bail_out} 

#
# Remake the tarball.
#
rm "${bin_tarball}" || ${bail_out}
${tar} -cvaf "${bin_tarball}" -C "${abs_destdir}" usr || ${bail_out}

rm -R -f "${templib}" || exit 1
