#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=readline

environment_variables=( )
configure_arguments=(
    --enable-multibyte
    --with-shared-termcap-library
)

source shared/basic.zsh
