#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=mpc
environment_variables=( )
configure_arguments=( --with-{gmp,mpfr}=/usr/local )

source shared/basic.zsh
