#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=gmp
environment_variables=( CFLAGS="${CFLAGS}${CFLAGS+ }-fomit-frame-pointer -std=gnu99" )
configure_arguments=( )

source shared/basic.zsh
