#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

#
# FIXME: There are some test failures. Some may be related to locales
#        and that we are not implementing locales very much. For now I
#        will not worry too much about it. I am installing gettext
#        merely to satisfy dependence on it. (It is not that I do not
#        take internationalization seriously. It is that I do not want
#        to deal with it right now. I have dealt with it before, and
#        thus know it is A LOT of extra detail.)
#

name=gettext

export LC_ALL=POSIX

environment_variables=( DC=gdc )
configure_arguments=(
    --disable-nls
    --enable-year2038
    --enable-c++
    --enable-d
    --enable-go=gcc
    --enable-modula2
    --enable-{acl,xattr}
    DC=gdc
)

source shared/basic.zsh
