#!/bin/zsh

source shared/make_package.zsh

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST"
    exit 2
fi

name=mit-scheme

_package_version="${package_version:-${1}}"
_targeted_host="${targeted_host:-${2}}"

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

packname="${name}-${_package_version}"
src_tarball="${abs_src_tarball_dir}/${packname}-x86-64.tar.gz"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_srcdirs_dir}/${packname}"
abs_builddir="${abs_srcdir}/src"
abs_destdir="${abs_srcdir}/___dest___"

mkdir -p "${abs_srcdirs_dir}"
rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
tar -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}
(

    cd "${abs_builddir}" || ${bail_out}
    env TARGETED_HOST="${_targeted_host}" \
        ./configure \
        --prefix=/usr/local \
        --enable-gdbm \
        || ${bail_out}
    make || ${bail_out}
    make install DESTDIR="${abs_destdir}" || ${bail_out}

    # Do not let MIT Scheme shadow Chez Scheme.
    rm -f "${abs_destdir}"/usr/local/bin/scheme

    #
    # The HTML documentation build system is broken, at least in
    # version 12.1.
    #
    cd ../doc || ${bail_out}
    ./configure --prefix=/usr/local --disable-html || ${bail_out}
    make || ${bail_out}
    make install-info install-pdf \
         DESTDIR="${abs_destdir}" || ${bail_out}
    rm -f "${abs_destdir}"/usr/local/share/info/dir

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
