#!/bin/zsh

if [[ $# -ne 5 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK ARCH TUNE"
    exit 2
fi

name=openssl

_package_version="${1}"
_targeted_host="${targeted_host:-${2}}"
_check="${3}"
_arch="${4}"
_tune="${5}"

tar=( tar --format=posix )
bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

jobs="${jobs:-24}"
check_jobs="${check_jobs:-"${jobs}"}"

packname="${name}-${_package_version}"
src_tarball="${abs_src_tarball_dir}/${packname}.tar.gz"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_srcdirs_dir}/${packname}"
abs_builddir="${abs_srcdir}"
abs_destdir="${abs_srcdir}/«dest»"

mkdir -p "${abs_srcdirs_dir}"
rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
${tar} -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}
mkdir -p "${abs_builddir}" || ${bail_out}
(

    cd "${abs_builddir}" || ${bail_out}

    _cppflags="-march=${_arch} -mtune=${_tune}"
    env CPPFLAGS="${_cppflags}" \
        ./config -fPIC shared \
        enable-{ktls,shared,pic,pie,tfo} \
        --prefix=/usr/local \
        linux-x86_64 || ${bail_out}
    make -j"${jobs}" || ${bail_out}
    if [[ "${_check}" != "no" ]] && [[ "${_check}" != "false" ]]; then
        make -j"${check_jobs}" test || ${bail_out}
    fi
    make -j"${jobs}" install DESTDIR="${abs_destdir}" || ${bail_out}

) || ${bail_out}
mkdir -p "${abs_bin_tarball_dir}" || ${bail_out}
${tar} -cvaf "${bin_tarball}" -C "${abs_destdir}" usr || ${bail_out}
