#!/bin/zsh

source shared/make_package.zsh
source shared/git.zsh

if [[ $# -ne 5 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK ARCH TUNE"
    exit 2
fi

name=bzip2

version="${1?}"
targeted_host="${2?}"
check="${3?}"
_arch="${4?}"
_tune="${5?}"

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

packname="${name}-${version}"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${targeted_host}.tar.zst"
bail_out=( exit 1 )

if [[ "${version}" != "1.0.8" ]]; then

    abs_repo_dir="${abs_src_tarball_dir}/${name}.git"
    git_check_out "${abs_repo_dir}" "${version}"

    abs_srcdir="${abs_repo_dir}"
    builddir="___build___"
    abs_builddir="${abs_srcdirs_dir}/${packname}/${builddir}"
    abs_destdir="${abs_srcdirs_dir}/${packname}/___dest___"

    rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
    install -d "${abs_builddir}" || ${bail_out}
    (
        cd "${abs_builddir}" || ${bail_out}

        cp --archive --link --update=none "${abs_srcdir}"/* "${abs_builddir}" \
            || ${bail_out}

        meson setup --prefix /usr/local "${builddir}" || ${bail_out}
        meson compile -C "${builddir}" || ${bail_out}
        if is_yes "${check}"; then
            meson test -C "${builddir}" --print-errorlogs
        fi
        meson install -C "${builddir}" --destdir "${abs_destdir}" || ${bail_out}

        (cd "${abs_destdir}/usr/local/lib/pkgconfig" && ln -s bz2.pc bzip2.pc)
    )

else

    src_tarball="${abs_src_tarball_dir}/${packname}.tar.gz"

    abs_srcdir="${abs_srcdirs_dir}/${packname}"
    abs_destdir="${abs_srcdir}/___dest___"

    make_arguments=( CC="gcc -fPIC -march=${_arch} -mtune=${_tune}" )

    mkdir -p "${abs_srcdirs_dir}"
    rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
    tar -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}
    (
        cd "${abs_srcdir}" || ${bail_out}
        make ${(@)make_arguments} || ${bail_out}
        make install ${(@)make_arguments} PREFIX="${abs_destdir}"/usr/local \
            || ${bail_out}
        make -f Makefile-libbz2_so ${(@)make_arguments} || ${bail_out}
        install -d "${abs_destdir}"/usr/local/share || ${bail_out}
        mv "${abs_destdir}"/usr/local/{man,share} || ${bail_out}
        install -d "${abs_destdir}"/usr/local/share/doc/"${name}" \
            || ${bail_out}
        install manual.{pdf,html} \
                "${abs_destdir}"/usr/local/share/doc/"${name}" \
            || ${bail_out}

    ) || ${bail_out}

fi

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
