#!/bin/zsh

#
# THIS PACKAGE HAS BEEN MADE OBSOLETE BY THE update-doas-that-does
# SCRIPT OF glibc-libre
#

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 PACKAGE_VERSION"
    exit 2
fi

targeted_host=x86_64-unknown-linux-gnu
check=no

name=opendoas

ban_enable_silent_rules=yes
ban_out_of_source_build=yes

function patch_function
{
    #
    # Change the safepath.
    #
    sed -i -E \
        '/safepath/s|/bin:/sbin:/usr/bin:/usr/sbin:|/run/wrappers/bin:/run/current-system/sw/bin:|' \
        doas.c

    #
    # Perform a couple of operations with root privileges.
    #
    sed -i -E \
        -e 's|^([[:space:]]+)chown|\1doas chown|' \
        -e 's|^([[:space:]]+)chmod|\1doas chmod|' \
        GNUmakefile

    #
    # To make a static doas, use our own libc script.
    #
    echo 'GROUP ( /usr/local/lib/libc.a )' > libc.so
}

export LIBRARY_PATH="`realpath .`:/usr/local/lib"

environment_variables=( )
configure_arguments=(
    --prefix=/usr/local
    --sysconfdir=/etc
    --without-pam               # Keep things simple. Avoid PAM.
    --with-shadow
    --build=x86_64-unknown-linux-gnu
    --host=x86_64-unknown-linux-gnu
    --target=x86_64-unknown-linux-gnu
)
make_arguments=( CFLAGS='-static' )

source shared/basic.zsh
