#!/bin/zsh

source shared/make_package.zsh
source shared/git.zsh

if [[ $# -ne 4 ]] && [[ $# -ne 5 ]]; then
    echo "Usage: $0 REVISION TARGETED_HOST ARCH TUNE [USE_CHICKEN_BOOT=no]"
    exit 3
fi

# Make CHICKEN Scheme from the Git sources.
name=chicken-core

_revision="${1}"
_targeted_host="${2}"
_arch="${3}"
_tune="${4}"
_use_chicken_boot="${5:-no}"

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

abs_repo_dir="${abs_src_tarball_dir}/${name}.git"
git_check_out "${abs_repo_dir}" "${_revision}"

packname="${name}-${_revision}"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_repo_dir}"
abs_builddir="${abs_srcdirs_dir}/${packname}/___build___"
abs_destdir="${abs_srcdirs_dir}/${packname}/___dest___"

rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
install -d "${abs_builddir}" || ${bail_out}
(
    cd "${abs_builddir}" || ${bail_out}

    # Out-of-source builds are not actually supported yet, as of
    # 2025-10-04. So copy the sources.
    cp --archive --link --update=none "${abs_srcdir}"/* "${abs_builddir}" \
        || ${bail_out}

    if [[ "${_use_chicken_boot}" != no ]] &&
           [[ "${_use_chicken_boot}" != false ]]; then
        chicken_boot_arguments="--chicken=/usr/local/libexec/chicken-core/chicken-boot"
    else
        chicken_boot_arguments=""
    fi

    env CFLAGS="-pipe -fPIC -O2 -march=""${_arch}"" -mtune=""${_tune}" ./configure \
        --prefix=/usr/local \
        --platform=linux \
        ${chicken_boot_arguments}

    make || ${bail_out}
    make check || ${bail_out}
    make install DESTDIR="${abs_destdir}" || ${bail_out}

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}

