#!/bin/zsh

source shared/make_package.zsh

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 PACKAGE_VERSION"
    exit 2
fi

name=aunit

_package_version="${1}"
_targeted_host=x86_64-unknown-linux-gnu

jobs="${jobs:-24}"

bail_out=( exit 1 )
gprbuild=( gprbuild -v )
gprinstall=( gprinstall -v )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

packname="${name}-${_package_version}"
src_tarball="${abs_src_tarball_dir}/${packname}.tar.gz"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_srcdirs_dir}/${packname}"
abs_builddir="${abs_srcdir}"
abs_destdir="${abs_srcdir}/___dest___"

install -d "${abs_srcdirs_dir}"
rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
tar -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}
install -d "${abs_builddir}" || ${bail_out}

(

    abs_docdir="${abs_destdir}/usr/local/share/doc/${name}"
    abs_infodir="${abs_destdir}/usr/local/share/info"

    cd "${abs_builddir}" || ${bail_out}

    make GPROPTS_EXTRA="-j${jobs} -v" || ${bail_out}
    make -C doc all || ${bail_out}

    make INSTALL="${abs_destdir}"/usr/local install || ${bail_out}

    install -d "${abs_docdir}" || ${bail_out}
    install README* COPYING* "${abs_docdir}" || ${bail_out}
    install doc/build/aunit_cb/pdf/aunit_cb.pdf "${abs_docdir}" || ${bail_out}
    install doc/build/aunit_cb/txt/aunit_cb.txt "${abs_docdir}" || ${bail_out}
    cp -R doc/build/aunit_cb/html "${abs_docdir}" || ${bail_out}
    cp -R examples "${abs_docdir}" || ${bail_out}

    install -d "${abs_infodir}" || ${bail_out}
    cp -R doc/build/aunit_cb/info/aunit_cb.info "${abs_infodir}" || ${bail_out}

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
