#!/bin/zsh

source shared/helpers.zsh
source shared/make_package.zsh
source shared/git.zsh

if [[ $# -ne 5 ]]; then
    echo "Usage: $0 REVISION TARGETED_HOST CHECK ARCH TUNE"
    exit 3
fi

name=libblake3

_revision="${1?}"
_targeted_host="${2?}"
_check="${3?}"
_arch="${4?}"
_tune="${5?}"

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

abs_repo_dir="${abs_src_tarball_dir}/BLAKE3.git"
git_check_out "${abs_repo_dir}" "${_revision}"

packname="${name}-${_revision}"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_repo_dir}"
abs_builddir="${abs_srcdirs_dir}/${packname}/___build___"
abs_destdir="${abs_srcdirs_dir}/${packname}/___dest___"

rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
install -d "${abs_builddir}" || ${bail_out}
(

    cd "${abs_builddir}" || ${bail_out}

    # Copy the sources.
    cp --archive --link --update=none "${abs_srcdir}"/* "${abs_builddir}" \
        || ${bail_out}

    cmake -S c -B c/build \
          -DCMAKE_C_FLAGS="-pipe -fPIC -O2 -march=${_arch} -mtune=${_tune}" \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
          -DCMAKE_INSTALL_RPATH=/usr/local/lib \
          -DBUILD_SHARED_LIBS=ON || ${bail_out}
    cmake --build c/build --target install \
          DESTDIR="${abs_destdir}" || ${bail_out}

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
