#!/bin/zsh

source shared/make_package.zsh
source shared/git.zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 REVISION TARGETED_HOST CHECK"
    exit 2
fi

name=ats2-itp-rootfinder

_revision="${1}"
_targeted_host="${2}"
_check="${3}"

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

abs_repo_dir="${abs_src_tarball_dir}/${name}.git"
git_check_out "${abs_repo_dir}" "${_revision}"

packname="${name}-${_revision}"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_repo_dir}"
abs_builddir="${abs_srcdirs_dir}/${packname}/___build___"
abs_destdir="${abs_srcdirs_dir}/${packname}/___dest___"

rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
install -d "${abs_builddir}" || ${bail_out}
(

    cd "${abs_builddir}" || ${bail_out}

    # Copy the sources.
    cp --archive --link --update=none "${abs_srcdir}"/* "${abs_builddir}" \
        || ${bail_out}

    # Autotoolize.
    ./autogen.sh || ${bail_out}
    env EXTRA_USR_LOCAL_CFLAGS=-O3 \
        ./configure \
        --prefix=/usr/local \
        --enable-silent-rules=yes \
        || ${bail_out}

    make -j"${jobs}" || ${bail_out}
    if [[ "${_check}" != "no" ]] && [[ "${_check}" != "false" ]]; then
        make check || ${bail_out}
    fi
    make install DESTDIR="${abs_destdir}" || ${bail_out}

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
