#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=attr

environment_variables=( )
configure_arguments=(
    --disable-nls
)

source shared/basic.zsh
