#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=tokyocabinet

ban_out_of_source_build=yes

environment_variables=( )
configure_arguments=(
    --enable-shared
    --enable-static
)

source shared/basic.zsh
