#!/bin/zsh

source shared/make_package.zsh

if [[ $# -ne 2 ]] && [[ $# -ne 4 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST ARCH TUNE"
    echo "       $0 PACKAGE_VERSION «binary»"
    exit 2
fi

name=sbcl

_package_version="${package_version:-${1}}"
_targeted_host="${targeted_host:-${2}}"
_arch="${3}"
_tune="${4}"

case "${_targeted_host}" in
    "«binary»" )
        _targeted_host=x86_64-unknown-linux-gnu
        _use_the_binary=yes
        ;;
    * )
        _use_the_binary=no
        ;;
esac

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

packname="${name}-${_package_version}"
if [[ "${_use_the_binary}" = "yes" ]]; then
    src_tarball="${abs_src_tarball_dir}/${packname}-x86-64-linux-binary.tar.bz2"
else
    src_tarball="${abs_src_tarball_dir}/${packname}-source.tar.bz2"
fi
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
if [[ "${_use_the_binary}" = "yes" ]]; then
    abs_srcdir="${abs_srcdirs_dir}/${packname}-x86-64-linux"
else
    abs_srcdir="${abs_srcdirs_dir}/${packname}"
fi
abs_builddir="${abs_srcdir}"
abs_destdir="${abs_srcdir}/«dest»"

mkdir -p "${abs_srcdirs_dir}"
rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
tar -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}
mkdir -p "${abs_builddir}" || ${bail_out}

(
    cd "${abs_builddir}" || ${bail_out}

    unset SBCL_HOME

    if [[ "${_use_the_binary}" = "yes" ]]; then
        install -d "${abs_destdir}/usr/local" || ${bail_out}
        INSTALL_ROOT="${abs_destdir}/usr/local" sh install.sh || ${bail_out}
    else
        export CC="gcc"
        export CFLAGS="-pipe -fPIC -march=${_arch} -mtune=${_tune}"
        sh make.sh --fancy || ${bail_out}
        (cd ./doc/manual && make || ${bail_out}) || ${bail_out}

        env INSTALL_ROOT="${abs_destdir}/usr/local" \
            LIB_DIR="${abs_destdir}/usr/local/lib" \
            DOC_DIR="${abs_destdir}/usr/local/share/doc/${name}" \
            sh install.sh || ${bail_out}
    fi

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
