#!/bin/zsh

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST"
    exit 2
fi

name=indent

ban_out_of_source_build=yes
ban_check=yes

environment_variables=( )
configure_arguments=(
    --disable-nls
)

source shared/basic.zsh
