#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=wolfssl

function patch_function
{
    sh ./autogen.sh

    #
    # Add our certificates directory.
    #
    nawk '{print}/static const char\* systemCaDirs\[\] = {/{print "\"/usr/local/etc/ssl/certs,\""}' \
         < src/ssl_load.c > src/ssl_load.c.tmp &&
        mv src/ssl_load.c{.tmp,}
}

environment_variables=( )
configure_arguments=(
    --enable-shared
    --enable-static

    --enable-ech
    --enable-dtls
    --enable-dtls-mtu
    --enable-quic
    --enable-libssh2
    --enable-openssh
    --enable-openvpn
)

source shared/basic.zsh
