#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=libffi

environment_variables=( )
configure_arguments=( --disable-builddir )

source shared/basic.zsh
