#!/bin/zsh

host=contact
arch=znver4
tune=znver4

bail_out=( exit 1 )

false && if ./make-zlib 1.3.1 ${host} yes ${arch} ${tune} ;then :;else ${bail_out};fi
false && if ./make-zstd 1.5.7 ${host} yes ${arch} ${tune} ;then :;else ${bail_out};fi
false && if ./make-binutils 2.45 ${host} yes ;then :;else ${bail_out};fi
false && if ./make-gmp 6.3.0 ${host} yes ;then :;else ${bail_out};fi
false && if ./make-mpfr 4.2.2 ${host} yes ;then :;else ${bail_out};fi
false && if ./make-mpc 1.3.1 ${host} yes ;then :;else ${bail_out};fi
false && if ./make-isl 0.27 ${host} yes ${arch} ;then :;else ${bail_out};fi
false && if ./make-gc 8.2.8 ${host} yes ;then :;else ${bail_out};fi
false && if ./make-gcc 15.2.0 ${host} all ;then :;else ${bail_out};fi
true && if ./make-gzip 1.14 ${host} yes ;then :;else ${bail_out};fi
true && if ./make-indent 2.2.13 ${host} ;then :;else ${bail_out};fi
true && if ./make-enscript 1.6.6 ${host} yes ;then :;else ${bail_out};fi
true && if ./make-c-intro-and-ref 0.1 ${host} yes ;then :;else ${bail_out};fi
