#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=libiconv

environment_variables=( )
configure_arguments=(
    --disable-nls

    --enable-static
    --enable-shared

    --enable-extra-encodings
    --enable-year2038
)

source shared/basic.zsh
