#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=libunistring

environment_variables=( )
configure_arguments=(
    #
    # Static-only libunistring, to simplify mixing it with different
    # packages.
    #
    --enable-static
    --disable-shared

    --enable-relocatable
    --enable-year2038
)

source shared/basic.zsh
