#!/bin/zsh

source shared/helpers.zsh
source shared/make_package.zsh
source shared/git.zsh

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 REVISION CHECK"
    exit 3
fi

name=tinycc

_revision="${1}"
_targeted_host=x86_64-unknown-linux-gnu
_check="${2}"

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

abs_repo_dir="${abs_src_tarball_dir}/${name}.git"
git_check_out "${abs_repo_dir}" "${_revision}"

packname="${name}-${_revision}"
bin_tarball="${abs_bin_tarball_dir}/${packname}-binary-for-${_targeted_host}.tar.zst"
abs_srcdir="${abs_repo_dir}"
abs_builddir="${abs_srcdirs_dir}/${packname}/«build»"
abs_destdir="${abs_srcdirs_dir}/${packname}/«dest»"

rm -R -f "${abs_srcdirs_dir}/${packname}" || ${bail_out}
install -d "${abs_builddir}" || ${bail_out}
(

    cd "${abs_builddir}" || ${bail_out}

    # Copy the sources.
    cp --archive --link --update=none "${abs_srcdir}"/* "${abs_builddir}" \
        || ${bail_out}

    # Patch a Makefile bug.
    sed -i 's|^XFLAGS-unx = -B\$(TOPSRC)$|XFLAGS-unx = -B$(TOPSRC) -I$(TOPSRC)/include|' \
        lib/Makefile

    gcc_version=`gcc --version|head -1 |sed 's/^.* //'`

    ./configure \
        --prefix=/usr/local \
        --sysincludepaths=/usr/local/lib/tcc/include:/usr/local/include:/usr/local/lib/gcc/x86_64-unknown-linux-gnu/"${gcc_version}"/include \
        --libpaths=/usr/local/lib/tcc:/usr/local/lib \
        --crtprefix=/usr/local/lib/tcc:/usr/local/lib \
        --elfinterp=/lib64/ld-linux-x86-64.so.2 \
        --config-new-dtags=yes \
        || ${bail_out}
    make || ${bail_out}
    if is_yes "${_check}"; then
        make test || ${bail_out}
    fi
    make install DESTDIR="${abs_destdir}" || ${bail_out}

) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
