#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=libtool

environment_variables=( )
configure_arguments=(
    --enable-ltdl-install
)

source shared/basic.zsh
