#!/bin/zsh

source shared/helpers.zsh
source shared/make_package.zsh

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 PACKAGE_VERSION"
    exit 2
fi

name=doas-sudo-shim

_package_version="${package_version:-${1?}}"

_dest_name="${dest_name:-___dest___}"

bail_out=( exit 1 )

abs_src_tarball_dir=`realpath "${PWD}/src_tarballs"`
abs_bin_tarball_dir=`realpath "${PWD}/bin_tarballs"`
abs_srcdirs_dir=`realpath "${PWD}/srcdirs"`

packname="${name}-${_package_version}"
src_tarball=`find_src_tarball "${abs_src_tarball_dir}/${packname}"` || ${bail_out}
bin_tarball="${abs_bin_tarball_dir}/${packname}-for-anybody.tar.zst"
abs_srcdir="${abs_srcdirs_dir}/${packname}"
abs_builddir="${abs_srcdir}"
abs_destdir="${abs_srcdir}/${_dest_name}"

mkdir -p "${abs_srcdirs_dir}"
rm -R -f "${abs_srcdir}" || ${bail_out}
tar -f "${src_tarball}" -C "${abs_srcdirs_dir}" -x || ${bail_out}
mkdir -p "${abs_builddir}" || ${bail_out}
(
    cd "${abs_builddir}" || ${bail_out}
    sed -i "1s|/bin/sh|/usr/bin/env sh|" sudo || ${bail_out}
    make man || ${bail_out}
    make install DESTDIR="${abs_destdir}"
) || ${bail_out}

make_package "${bin_tarball}" "${abs_destdir}" || ${bail_out}
