#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=nghttp3

environment_variables=( )
configure_arguments=(
    --enable-lib-only
)

source shared/basic.zsh
