#!/bin/zsh

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 PACKAGE_VERSION TARGETED_HOST CHECK"
    exit 2
fi

name=nghttp2

environment_variables=( )
configure_arguments=(
    --with-libng{tcp2,http3}
    --with-libbrotli{enc,dec}
)

source shared/basic.zsh
